#!/bin/bash
set -Eeuo pipefail;
########################################################################
#	Copyright (C) 2020        Alejandro Colomar Andres
#	SPDX-License-Identifier:  GPL-2.0-only
########################################################################

synopsis="${BASH_SOURCE[0]} [OPTION]... NAMESPACE";

usage="\
Usage:  ${synopsis}
Try '${BASH_SOURCE[0]} -h' for more information.";

help="\
SYNOPSIS
	${synopsis}

DESCRIPTION
	Deploy kubernetes stack from <etc/kubernetes/manifests/*.yaml>,
	using configs and secrets from <run/{configs,secrets}/PROJECT/>.

	Root permissions are required to copy files to /run.

OPTIONS
	-h	Print this help and exit.

	-k=KUBECTL
		Use a different kubectl (default is 'kubectl').

	-v	Verbose output.

ERRORS
	EX_USAGE
		Invalid or missing arguments or options.

	EX_NOINPUT
		The directory <etc/kubernetes/manifests/> does not exist.

	EX_NOPERM
		Not enough permissions.
";

EX_OK=0;
EX_USAGE=64;
EX_NOINPUT=66;

v='';
while getopts 'hk:v' opt; do
	case ${opt} in
	h)	echo "${help}";
		exit ${EX_OK};
		;;
	k)	k="${OPTARG}";
		;;
	v)	v='-v';
		;;
	?)	>&2 echo "${usage}";
		exit ${EX_USAGE};
		;;
	esac;
done;
shift $((${OPTIND} - 1));

if [ $# -ne 1 ]; then
	>&2 echo "${usage}";
	exit ${EX_USAGE};
fi;
n="$1";

! [ -d etc/kubernetes/manifests/ ] \
	&&exit ${EX_NOINPUT};

"${k:-kubectl}" create namespace "${n}";

_d="$(dirname "${BASH_SOURCE[0]}")";
${_d}/../kubernetes/create_configmaps	${v} -n "${n}" ${k:+-k} ${k} ||:;
${_d}/../kubernetes/create_secrets	${v} -n "${n}" ${k:+-k} ${k} ||:;

find -L "etc/kubernetes/manifests/" -type f \
|sort -V \
|while read -r f; do
	"${k:-kubectl}" apply -f "${f}" -n "${n}";
done;

exit ${EX_OK};
