#!/bin/bash
set -Eeuo pipefail;
########################################################################
#	Copyright (C) 2020        Alejandro Colomar Andres
#	SPDX-License-Identifier:  GPL-2.0-only
########################################################################

synopsis="${BASH_SOURCE[0]} [OPTION]... PROJECT";

usage="\
Usage:  ${synopsis}
Try '${BASH_SOURCE[0]} -h' for more information.";

help="\
SYNOPSIS
	${synopsis}

DESCRIPTION
	Deploy openshift stack from <etc/openshift/manifests/*.yaml>,
	using configs and secrets from <run/{configs,secrets}/PROJDIR/>.

	Root permissions are required to copy files to /run.

OPTIONS
	-h	Print this help and exit.

	-v	Verbose output.

ERRORS
	EX_USAGE
		Invalid or missing arguments or options.

	EX_NOINPUT
		The directory <etc/openshift/manifests/> does not exist.

	EX_NOPERM
		Not enough permissions.
";

EX_OK=0;
EX_USAGE=64;
EX_NOINPUT=66;

v='';
while getopts 'hk:v' opt; do
	case ${opt} in
	h)	echo "${help}";
		exit ${EX_OK};
		;;
	v)	v='-v';
		;;
	?)	>&2 echo "${usage}";
		exit ${EX_USAGE};
		;;
	esac;
done;
shift $((${OPTIND} - 1));

if [ $# -ne 1 ]; then
	>&2 echo "${usage}";
	exit ${EX_USAGE};
fi;
p="$1";

! [ -d "etc/openshift/manifests/" ] \
	&&exit ${EX_NOINPUT};

oc new-project "${p}";

_d="$(dirname "${BASH_SOURCE[0]}")";
${_d}/../openshift/create_configmaps	${v} ||:;
${_d}/../openshift/create_secrets	${v} ||:;

oc apply -Rf etc/openshift/manifests/ -n "${p}";

exit ${EX_OK};
